game status en shipsdropdown , voorlopig, werkt nog niet, kan jij dez…
Thijssens/Zeeslagje pull request #6
Opened 2024-10-30 08:37 UTC by kristofdeman

wil jij deze even bekijken of dit juiste is , 
want krijg deze niet direct goed

2024-10-30 14:07 UTC, Thijssens commented
Je functies sowieso niet omdat je ze nergens oproept.

2024-10-30 14:11 UTC, Thijssens requested changes
je moet eerst nog de functies oproepen om ze te laten werken. dan ga je misschien nog steeds foutmeldingen moeten oplossen, maar dan heb je tenminste iets

2024-10-31 08:57 UTC, kristofdeman commented
heb een extra button toegevoegd in html en js , zodat we de gamestatus handmatig kunnen ophalen, enkel in console log

2024-10-31 14:10 UTC, Thijssens approved these changes
ziet er al goed uit, er zitten wel een paar rare ifs waar ik het nut niet echt van snap, en we zouden ook de secret variabele uit de global scope moeten halen. Dit zijn echter maar details die later kunnen gefixt worden.

2024-10-31 14:11 UTC, Thijssens approved these changes

2024-10-31 14:11 UTC, merged